[revisions]
revset = "present(@) | ancestors(immutable_heads().., 7) | present(trunk())"

[ui]
theme = "base16-gruvbox-material-dark-hard"
flash_message_display_seconds = 2

[preview]
show_at_start = false
width_percentage = 55

[custom_commands]
"copy bookmark" = { args = [ "util", "exec", "--", "jjui-copy-bookmark.sh", "$change_id" ], key = ["y"] }
"open PR" = { args = [ "util", "exec", "--", "jjui-gh-pr.sh", "$change_id" ], show = "interactive", key = ["p"] }
"merge PR" = { args = [ "util", "exec", "--", "jjui-gh-pr-merge.sh", "$change_id" ], show = "interactive", key = ["m"] }
