[ui]
theme = "base16-gruvbox-material-dark-hard"

[preview]
show_at_start = false
width_percentage = 55

[custom_commands]
"open PR" = { args = [ "util", "exec", "--", "jjui-gh-pr.sh", "$change_id" ], show = "interactive", key = ["p"] }
"merge PR" = { args = [ "util", "exec", "--", "jjui-gh-pr-merge.sh", "$change_id" ], show = "interactive", key = ["m"] }
