[settings]
cache_prune_age = "7d"
experimental = true
gpg_verify = true
jobs = 24
idiomatic_version_file_enable_tools = ["rust"]
disable_backends = ["asdf"]
python.uv_venv_auto = true
npm.package_manager = "bun"

[tools]
claude-code = "latest"
"github:vectordotdev/vector" = "latest"
python = "3.14.3"
"github:open-telemetry/opentelemetry-collector-releases"= { version = "latest", asset_pattern = "otelcol-contrib_*_darwin_arm64.tar.gz" }
age = "latest"
"github:zippoxer/recall" = "latest"
istioctl = "latest"
lua-language-server = "latest"
"go:golang.org/x/tools/gopls" = "latest"
ruff = "latest"
tinymist = "latest"
helm-ls = "latest"
golangci-lint = "latest"
yamllint = "latest"
stylua = "latest"
golines = "latest"
shfmt = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"github:astral-sh/ty" = "latest"
gemini-cli = "latest"
"github:arttor/helmify" = "latest"
helm-diff = "latest"
helm = "latest"
typst = "latest"
typstyle = "latest"
uv = "latest"
tree-sitter = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bun = "latest"
just = "latest"
kafkactl = "latest"
kubectl = "latest"
kustomize = "latest"
krew = "latest"
"github:ente-io/ente" = { version = "v0.2.3", version_prefix = "cli-" }
"github:joshmedeski/sesh" = "latest"
"github:ivaaaan/smug" = "latest"
zoxide = "latest"
atuin = "latest"
glow = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
rg = "latest"
ripgrep-all = "latest"
"github:walles/moor" = "latest"
gh = "latest"
pint = "latest"
lazygit = "latest"
jq = "latest"
neovim = "latest"
viddy = "latest"
duf = "latest"
jqp = "latest"
dust = "latest"
"github:dalance/procs" = "latest"
"github:prometheus/prometheus" = { version = "latest", filter_bins = "promtool" }
delta = "latest"
yq = "latest"
jjui = "latest"
jj = "latest"
"github:grafana/loki" = { version = "latest", asset_pattern = "logcli-darwin-arm64.zip", bin = "logcli" }
magika = "latest"
"github:bschaatsbergen/cidr" = "latest"
"github:hmans/beans" = "latest"
websocat = "latest"
grpcurl = "latest"
"github:eduardofuncao/pam" = "latest"
"github:DeprecatedLuar/better-curl-saul" = "latest"
"github:aaronriekenberg/rust-parallel" = "latest"
tilt = "latest"
cargo-binstall = "latest"
"cargo:https://github.com/sharkdp/vivid" = "latest"
"cargo:eza" = "latest"
"cargo:csvlens" = "latest"
"github:raine/workmux" = "latest"
redis = "latest"
"http:fzf-tmux" = { version = "0415fa8", url = "https://raw.githubusercontent.com/junegunn/fzf/9725eac314551072538c06ef914a0e7bedf19018/bin/fzf-tmux" }
"github:kavehtehrani/cloudflare-speed-cli" = "latest"
"github:backnotprop/plannotator" = "latest"
"cargo:jj-vine" = "latest"
ast-grep = "latest"
amp = "latest"
"npm:@openai/codex" = "latest"
"npm:yaml-language-server" = "latest"
"npm:pixelhq" = "latest"
