[settings]
cache_prune_age = "7d"
experimental = true
gpg_verify = true
jobs = 24
idiomatic_version_file_enable_tools = ["rust"]
disable_backends = ["asdf"]
python.uv_venv_auto = true

[tools]
"cargo:csvlens" = "latest"
"cargo:eza" = "latest"
claude-code = "latest"
cmake = "3.31.9"
"github:vectordotdev/vector" = "latest"
"npm:@just-every/code" = "latest"
"npm:@openai/codex" = "latest"
"npm:cchistory" = "latest"
"npm:renovate" = "latest"
python = "3.13.7"
tilt = "latest"
"github:open-telemetry/opentelemetry-collector-releases"= { version = "latest", asset_pattern = "otelcol-contrib_*_darwin_arm64.tar.gz" }
age = "latest"
